### ISSUE TITLE
Compilation error - missing p4 file

### ISSUE THREAD

**Issue by signorello** [eniac/Speedlight#1]
Compiling your code (any of the main Ptk*.p4 files ) raises the following error:

$~ p4c --target bmv2 --arch v1model --std p4-14 Pkt.p4 
Pkt.p4:23:10: fatal error: ../out/config.p4: No such file or directory
 #include "../out/config.p4"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.

because of a missing "config.p4" file. Please apologize me and ignore this, if that file is somehow auto-generated by some of the other scripts you provide, I have just tried to compile your p4 code.

**Comment by NofelYaseen** [comment]
config file is generated using `p4src/utilities/generate_p4vars.py`.

There are instructions on how to run in readme file, pasting here for convenience. 

### Compiling the dataplane ###

This release has been tested on Ubuntu 16.04 LTS, but should work on Ubuntu 14.04+.
p4 simluator has a large memory requirement. We used it in 32gb RAM.
The following instructions assume 3 windows: (1) switch behavioral model, (2) notification listener, and (3) snapshot initiation script.

1. Setup.
	```
	# Installs all prerequisites and compiles the Speedlight dataplane, including:
	# https://github.com/p4lang/behavioral-model/commit/66cefc5e901eafcebb0e1a8f681a05795463215a
	# https://github.com/p4lang/p4c-bm/commit/d75624e18f4ae79e9e5cb478c33d221711f76574
	# Also sets up the virtual network interfaces for BMv2
	./setup.sh
	```

2. Compile and run the Speedlight dataplane.
	```
	# <VARIANT>            {Pkt, Pkt_W, Pkt_WC}
	# <NUM_PORTS>          Number of ports in the switch.
	# <MAX_SNAPSHOT_ID>    Highest valid snapshot ID. Without wraparound (*_W),
	#                      behavior above this value is undefined. With wraparound,
	#                      this number determines the maximum number of outstanding
	#                      snapshots.
	./start_switch.sh <VARIANT> <NUM_PORTS> <MAX_SNAPSHOT_ID>
	# Leave this window open
	```

3. In a new window, install the match-action rules and start listening for notifications.
	```
	# <VARIANT>            {Pkt, Pkt_W, Pkt_WC}. Must match parameter given to
	#                      start_switch.sh.
	./start_listening.sh <VARIANT>
	# Leave this window open.  Notifications will output here.
	```

4. In a third window, initiate a snapshot.
	```
	# <HH>                 Hour of snapshot according to the Unix date command
	# <MM>                 Minute of snapshot according to the Unix date command
	# <NUM_PORTS>          Number of ports in the switch. Must match parameter given
	#                      to start_switch.sh.
	# This will initiate a single snapshot with ID = 1 in a parallel fashion.
	# Port responsibilities are spread across available cores to increase the 
	# speed at which we can issue a sequence of snapshot initiations.
	# Example: ./start_snapshot 17 09 10
	# This will take snapshot for 10 ports at time 5:09 pm.
	./start_snapshot.sh <HH> <MM> <NUM_PORTS>

	# You can also access the original, more flexible snapshot initiation 
	# that is compiled to the following program.  This one is required for
	# subsequent snapshots, etc.
	out/startsnap
	```
